_harp/acerca.ejs, _harp/css/custom.css
@julianduque @edsadr @academo fixed!
=>  Remove JS logic from Acerca de view and fix layout

_harp/posts/_data.json
@edsadr @julianduque guys, please review and merge ^^
=> Update my bio

_harp/_footer.ejs
Two changes:
- Added script to update copyright date automatically
- Fix Villavicencio link
This PR replaces #65
=> Added script to update copyright date, fix URL

_harp/_data.json, _harp/posts/_data.json
=> orange member profile

_harp/_data.json, _harp/posts/_data.json, events.js
add jessecogollo like voluntary. and fix meetup api events, when meetup return a message without result key.
=> add voluntary and fix error.

_harp/heroes/_data.json
I'm just adding myself to the heroes section with the slide of my presentation
=> Add Mateo Calle to heroes (with slide)

.gitignore, _harp/_data.json, _harp/heroes/_data.json, _harp/posts/_data.json, _harp/posts/nodeschool-aprende-por-tu-cuenta.md, package.json
- Post about NodeSchool
- Added Maria Fernanda Serna to the list of heroes
- I include myself inside the organizers **
** I was included in the organizers of MedellinJS because I want to participate more actively in the community by helping in other topics besides the talks, such as events, blogs, ideas, etc. I hope you do not dislike the invitation, but I want to contribute a lot More to the community.
=> Added new hereo and post about nodeSchool

GOVERNANCE.md
Add Governance document `GOVERNANCE.md`, as specified in [Issue #98](https://github.com/coljs/medellinjs/issues/98).
=> Add Open Government Guidelines

_harp/heroes/_data.json
@jessecogollo add the thumbnails please! 👍
=> Add presentations

components/AppFooter.vue, components/AppOrganizer.vue, pages/index.vue
the first step, what do you think about how to get the data, using hard code object or use some service to get the data like is used at JSConfCO?
=> update medjs socialmedia footer and first phase issue #112

components/AppCommunities.vue, pages/index.vue
=> implementation communities setcion #114

assets/js/scroll-to.js, assets/scss/base.scss, components/AppHeader.vue, components/AppNavBar.vue
Functionality in this PR: :boom: :boom: :boom:
- Add the smooth scroll to navigate between sections of the page
=> Add the smooth scroll

README.md, components/AppNavBar.vue, components/AppNextMeetups.vue, package-lock.json, package.json, pages/index.vue
- Resuelve el issue #150 
- Añade jsonp como dependencia para poder hacer el llamado al API de meetup
=> Add next meetups section and update it from the Meetup API

.all-contributorsrc, README.md, package-lock.json, package.json
Add the Team organizators and contributors to website
=> Add the list contributors new version

components/AppHeader.vue, components/AppNavBar.vue, package-lock.json
#148 Quite la tilde de MedellinJS Tilde
=> #148 Quite la tilde de MedellinJs Titulo

components/AppNavBar.vue
Se agrega botón para ir al chat de gitter medellinjs
=> Se agrega boton para ir al chat de gitter medellinjs #152

.gitignore, README.md, components/AppCommunities.vue, yarn.lock
Hubo una clase que estaba generando un scroll horizontal, descrito en el issue #162
La solución fue quitarlo y no hubo ningún cambio que afecte el diseño ;)
Además agregué que ignore todos los logs en el git ignore.
Como usé Yarn, agregué en yarn.lock.
Gracias!.
=> Fix issue #162

components/AppHeroes.vue
[Issue #149](https://github.com/coljs/medellinjs/issues/149)
=> #149 add modal properties for responsive in mobile

components/AppNavBar.vue, package-lock.json
No lo puse en el Footer porque no queda bien con la temática de los vínculos a las redes sociales.
=> Integración de link a archivo de cuentas (Google docs) -> Issue #146

pages/comparte.vue
Realice una pagina "comparte.vue" que contiene el contenido del componente del formulario de las charlas., mostrando esa sección en el enlace medellinjs.org/comparte.
Quedo atento a cualquier comentario.
=> Seccion contacto al enlace medellinjs.org/comparte. #147 

assets/scss/base.scss
Hola. 
Como aporte personal a la pagina de MedellinJS quise realizar una animación en el cubo que aparece en el banner principal de la pagina.
Espero les guste y lo agreguen .
=> Rotación de cubo de MEDJS 5 Años

nuxt.config.js, package.json
#174  Implemente el siguiente modulo [](https://github.com/nuxt-community/analytics-module)
=> Integracion Google Analytics #174 

assets/data/heroes.js, assets/data/organizadores.js
adjunto mi charla del mes de octubre del 2017 a Heroes y modifico la descripción de mi card en Organizadores
=> adjunto mi charla de ionic y modifico mi card

assets/scss/base.scss, components/AppSponsors.vue
He removido la textura del fondo para no sobre cargar la portada! 
* se agrega una linea extra para que en responsiva los enlaces de partners no se corten
#210
=> Portada sin textura 

assets/data/heroes.js
With data for the "WebAssembly 101" presentation
=> Added @elyalvarado to heroes data

assets/data/heroes.js, pages/sorteo/index.vue
Fix issue #229 
Update Heroe jdmaldonado
=> Improve "Sorteo" page

assets/data/heroes.js
Hola!
Me agrego como speaker al sitio!
Gracias!
=> update: add hero romelperez

components/AppHeader.vue
=> changed the 5 for the 6

components/AppSponsors.vue, package-lock.json
Not sure, but maybe for Matter Supply we are going to need a better logo.
=> adding mattersupply and colombiadev as sponsors

pages/sorteo/index.vue
In the sorteo page, show only active meetups
=> Sorteo: Show Active meetups

assets/data/heroes.js
Just want to fix my GitHub profile link. :)
=> fix hero - Cristian Martinez

assets/data/heroes.js
Permission is requested to modify the heroes file and update the page to add Catalina Meneses to this section.
=> Adding Catalina Meneses to the section of heroes

.travis.yml, components/AppSponsors.vue
Adds NodeSource to sponsors in landig page.
=> Adds NodeSource as sponsor

components/organization/documents.vue
Improve identation in file, also add . symbol at the end of paragraph
=> add . at the end of the paragraph

assets/data/heroes.js, components/AppSponsors.vue
=> URL images were verified and checked

README.md
=> Add Badges travisci.org and davidm.org

assets/scss/base.scss, components/AppSponsors.vue
Adjust sponsor images, now they look like this:
=> adjust images size for sponsors

components/AppSponsors.vue
Closes #(numero de issue asociado)
Colocar la información que considere pertinente del cambio que se está subiendo, por ejemplo una captura de pantalla si es algún cambio visual que quiera resaltar.
=> <components AppSponsors.vue> change logo url

pages/sorteo/index.vue
The page will now display the raffle for the latest event
created on https://meetup-raffles.now.sh
=> Change "Sorteo" page to use meetup-raffle-widget

components/AppSponsors.vue, pages/sorteo/index.vue
=> deploy to production

assets/data/heroes.js
Actualizar wrong url de mi avatar 👍
=> Update nicholls avatar

components/AppSponsors.vue
Closes 
Soluciona #321 
[https://ibb.co/28DNTfS](url)
=> Nuevo sponsors

components/AppSponsors.vue
=> 269 - Fixed sponsor name typo.

assets/scss/base.scss, components/AppSponsors.vue
Closes #271
Clase nueva creada para los nombres de los patrocinadores.
=> 271 - Sponsor capitalization

assets/data/communities.js, assets/scss/base.scss, components/AppCommunities.vue, package-lock.json
Closes #326 
- Mejoras en el layout de la sección _comunidades_
- Las urls de las comunidades llevan a la url correcta
=> [#326] Algunas comunidades llevan a la url equivocada

assets/data/heroes.js
Actualizando la url de la imagen ya que no esta cargando en medellinjs.org. Y usando solo el primer apellido.
[Deploy preview 382](https://deploy-preview-382--medellinjs.netlify.com/)
=> Update heroes.js (Informacion: Samuel Burbano)

nuxt.config.js, package-lock.json, package.json
Update the code for PWA with the current version of Nuxt.js
[Deploy preview 427](https://deploy-preview-427--medellinjs.netlify.com/)
=> Update the PWA files

components/AppSponsors.vue
=> Release June

pages/sponsor-en/index.vue, pages/sponsor/index.vue
pdf sponsorship plan file updates with new brand
=> link to sponsors pdf updated

assets/data/heroes.js
Michel Linares added as hero for your talk about **Sobreviviendo a una entrevista de JavaScript**
[Deploy preview ###](https://deploy-preview-###--medellinjs.netlify.com/)
*Please change the ### for the number of the `pull request`, after that you can delete this line*.
=> michel linares added as hero

assets/data/heroes.js
some hero avatars fixed
[Deploy preview ###](https://deploy-preview-###--medellinjs.netlify.com/)
*Please change the ### for the number of the `pull request`, after that you can delete this line*.
=> img hero profiles fixed

assets/data/organizadores.js
- Adding Christian Camilo Galeano co-organizer card
=> Add Camilo Galeano co-organizer card
